import { Product } from "./types";

// Catálogo original migrado desde el sitio estático ARIDA ERIUS,
// ahora como el estado inicial ("seed") de la base de datos ligera.
export const seedProducts: Product[] = [
  {
    id: "prod-01",
    name: "CHROME SPINE TRENCH",
    category: "outerwear",
    tag: "OUTERWEAR // .925 HARDWARE",
    description:
      "Lana virgen italiana con vértebras articuladas en plata esterlina .925 a lo largo del espaldar.",
    priceBaseEUR: 2850,
    image: "/assets/floating_chrome_trench.png",
    hasSizes: true,
    sizes: ["S", "M", "L", "XL"],
    stock: 6,
    status: "visible",
    updatedAt: Date.now(),
  },
  {
    id: "prod-02",
    name: "HEAVY HOODIE OVERSIZED 650 GSM",
    category: "streetwear",
    tag: "STREETWEAR // 650 GSM",
    description:
      "Algodón denso japonés 650 GSM con bordado tribal gótico tonal y silueta rígida estructurada.",
    priceBaseEUR: 480,
    image: "/assets/floating_hoodie_noir.png",
    hasSizes: true,
    sizes: ["S", "M", "L", "XL"],
    stock: 14,
    status: "visible",
    updatedAt: Date.now(),
  },
  {
    id: "prod-03",
    name: "ANILLO TRIBAL AE .925",
    category: "hardware",
    tag: "PLATA .925 // FORJADO EN FRÍO",
    description:
      "Plata esterlina maciza patinada a mano con heráldica de dragones y cruz tribal oxidada.",
    priceBaseEUR: 390,
    image: "/assets/floating_tribal_ring.png",
    hasSizes: false,
    sizes: [],
    stock: 9,
    status: "visible",
    updatedAt: Date.now(),
  },
  {
    id: "prod-04",
    name: "ACID WASH MINERAL BOXY TEE",
    category: "streetwear",
    tag: "STREETWEAR // MINERAL WASH",
    description:
      "Algodón orgánico pesado con desgaste mineral artesanal y sello gótico en serigrafía cero tacto.",
    priceBaseEUR: 260,
    image: "/assets/floating_acid_tee.png",
    hasSizes: true,
    sizes: ["S", "M", "L", "XL"],
    stock: 20,
    status: "visible",
    updatedAt: Date.now(),
  },
  {
    id: "prod-05",
    name: "BOMBER LEATHER OBSIDIAN",
    category: "outerwear",
    tag: "OUTERWEAR // OBSIDIAN LEATHER",
    description:
      "Cuero curtido de grano completo con zíperes dobles forjados en plata esterlina y tiradores de calavera.",
    priceBaseEUR: 1700,
    image: "/assets/floating_leather_bomber.png",
    hasSizes: true,
    sizes: ["S", "M", "L", "XL"],
    stock: 4,
    status: "visible",
    updatedAt: Date.now(),
  },
  {
    id: "prod-06",
    name: "RAW SELVEDGE DISTRESSED DENIM",
    category: "streetwear",
    tag: "STREETWEAR // 16 OZ DENIM",
    description:
      "Denim rígido japonés 16oz con desgaste artesanal individualizado y remaches de plata fundida.",
    priceBaseEUR: 530,
    image: "/assets/floating_raw_denim.png",
    hasSizes: true,
    sizes: ["S", "M", "L", "XL"],
    stock: 0,
    status: "upcoming",
    updatedAt: Date.now(),
  },
];
